### ISSUE TITLE
Request for the documentation of using Creator with Firebase Authentication and Firebase Firestore

### ISSUE THREAD

**Issue by rhc** [liangxianzhe/creator#12]
A more complex example with Firebase will accelerate the adoption of the newly created library.
The example should include at least 3 layers: UI, logic (with Creator), and repo (interface with Firebase API).

**Comment by liangxianzhe** [comment]
Makes sense. Will add one example.

**Comment by liangxianzhe** [comment]
Hey @rhc , what do you think about this https://github.com/liangxianzhe/creator/tree/master/packages/creator/example_starter ?

**Comment by liangxianzhe** [comment]
@Kypsis @iamshaunwu In case you want to take a look since you mentioned examples before :)
