### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by loic-hamdi** [liangxianzhe/creator#13]
Hi,

I don't see any Discord server in the readme, it could be a great option to help and grow the community.

**Comment by qronos-ai** [comment]
Well, I guess it may be too early at this stage. Moreover, handholding a community is not easy unless there are more volunteers. Have you already tried Creator?

**Comment by liangxianzhe** [comment]
Agree with @iamshaunwu, we can create a discord server when the community is bigger. For now, maybe let's just use Github issues.

**Comment by loic-hamdi** [comment]
@iamshaunwu @liangxianzhe  👍
