### ISSUE TITLE
Observe Creator dispose events

### ISSUE THREAD

**Issue by diegosz** [liangxianzhe/creator#16]
First, many thanks for this library, like it a lot, I was looking something to migrate away from Getx, was pondering on using Riverpod, but luckily found Creator. It's simple to grasp and easy to onboard a dev team starting with Flutter.

While migrating some controllers, one thing that help me fully understand the lifecycle of the Creator values was using a custom observer that also prints the dispose events  because the default observer skips those events.

This post is only to record this so it could help someone else.

The custom observer:

```dart
class CustomCreatorObserver extends DefaultCreatorObserver {
  const CustomCreatorObserver();

  @override
  void onDispose(CreatorBase creator) {
    if (ignore(creator)) {
      return;
    }
    print('[Creator] Dispose: ${creator.infoName}');
  }
}
```

And you could use it like this:

```dart
void main() {
  runApp(CreatorGraph(
    child: const MyApp(),
    observer: const CustomCreatorObserver(),
  ));
}
```

Cheers,
Diego

**Comment by liangxianzhe** [comment]
Thanks for posting this @diegosz, I'm glad Creator could help!

**Comment by liangxianzhe** [comment]
Hi @diegosz FYI I added more options for logging https://github.com/liangxianzhe/creator/commit/28ab50d2a287acea71cf703e1a6f2c784df93154
