### ISSUE TITLE
Force-Update state of an emitter? 

### ISSUE THREAD

**Issue by algorithmiker** [liangxianzhe/creator#19]
hey @liangxianzhe !
Sorry for bothering. I wanted to ask how the following could be written in Creator:

I want a Creator/Emitter that has the ID of the currently selected account.
Initially, before it is set, it should return the ID of the first account found in the database.

This is what I have right now:
```dart

  static final selectedC = Emitter<FoiledSelectedAccount>(
    (ref, emit) async => FoiledSelectedAccount.init(ref, emit),
  );
  
class FoiledSelectedAccount {
  int current;
  Ref ref;
  Function(FoiledSelectedAccount) emit;
  FoiledSelectedAccount._(this.ref, this.emit, this.current);
  static Future<FoiledSelectedAccount> init(
      Ref ref, Function(FoiledSelectedAccount) emit) async {
    var first = await ref.read(Account.firstIDC);
    var n = FoiledSelectedAccount._(ref, emit, first);
    emit(n);
    return n;
  }

  void set(int nw) {
    current = nw;
    emit(this);
  }
}
 ```

and then later in the code
```dart
(await ref.watch(selectedC)).set(2);
```

my question is: Could this be written more elegantly? **If we could force-update the state of an `Emitter` from somewhere else, it could be used like this**

```dart
static final selectedC = Emitter<int>((ref, emit) {
  var first = await ref.read(Account.firstIDC);
  emit(first);
})


// then later in the code
ref.read(selectedC).forceUpdate(2);
```
**`ref.set()` seems to only work with `Creator`, not `Emitter`.**
Any ideas? thanks for your time.

**Comment by liangxianzhe** [comment]
Hi. Have you seen [this](https://github.com/liangxianzhe/creator/blob/master/packages/creator_core/lib/src/ref.dart#L165-L171)? Sorry it seems I didn't add it to the Readme.
