### ISSUE TITLE
Deprecate group (.arg)

### ISSUE THREAD

**Issue by liangxianzhe** [liangxianzhe/creator#21]
I plan to deprecate the creator group feature (Creator.arg1, Creator.arg2, etc) in favor of [Creator equality](https://github.com/liangxianzhe/creator#creator-equality).

The reason is to remove complexity and offers more flexibility. 

Before:
```
final tabCreator = Creator.arg1<Tab, String>((ref, userId) => 'instagram');
```

After:
```
Creator<String> tabCreator(String userId) => Creator.value('instagram', args: ["tab", userId]);
```

`.arg` uses creator equality under the hood. The new method removes the odd syntax of `arg1`. Users can just use a normal function to create a group of creators and organize the group however they want, for example, put them in a Set and have a function to `recreateAll`, etc.

**Comment by CalsRanna** [comment]
I use creator a lot, and I don't think this is a good way to do so.
Here code before:
```Dart
final surgeriesEmitter = Emitter.arg1<List<Surgery>, int>(
  (ref, page, emit) async {
    final surgeries = await SurgeryApi().getSurgeries(page);
    emit(surgeries);
  },
  name: (page) => 'surgeriesEmitter_page_$page',
);
```
Here's code after:
```Dart
Emitter<List<Surgery>> surgeriesEmitter(int page) => Emitter(
      (ref, emit) async {
        final surgeries = await SurgeryApi().getSurgeries(page);
        emit(surgeries);
      },
      args: [page],
      name: 'surgeriesEmitter_page_$page',
    );
```
Maybe you guys think use function to return data may works more expected. But in the real coding, how the code can be orginazed and formatted well is kinda important to.And, since it's a function, I give params in the function caller, why should I declare args specified in another params?It confuse.
So maybe, it it's not the best way to solve group problem.

**Comment by CalsRanna** [comment]
And the new version to declare a creator may cause confusion, cause the normal creator is a param and the grouped creator is a function, kinda complicated.
All that above is, a new way to do this maybe better.

**Comment by liangxianzhe** [comment]
Hi @CalsRanna, thanks for the feedback.

I agree with you that setting both the function parameter and `args` parameter is a little bit confusing. And BTW, in your example, you probably want `args: ["surgeries", page]`, instead of `args: [page]`, to make the args unique.

I don't fully agree with your second comment. Even in the old approach, the normal creator can be used directly while grouped creator needs to be used by passing in a parameter like a function. In this regard, it is similar to the new approach in terms of complexity.

One nice thing about the new approach is that the creator doesn't need to be a global variable, which has more flexibility. For example, I can make it part of the `SurgeryApi` class:
```dart
extension SurgeryApiCreators extends SurgeryApi {
  Emitter<List<Surgery>> pageCreator(int page) => Emitter(
      (ref, emit) async {
        final surgeries = await getSurgeries(page);
        emit(surgeries);
      },
      args: ["sugeries", page],
      name: 'surgeriesEmitter_page_$page',
    );
}
```

I'm going to re-open this issue while searching for a better solution.

**Comment by liangxianzhe** [comment]
One improvement has been made that if `args` will be used for naming if `name` is missing. In the previous example, if we don't set `name`, the name of the emitter would be `sugeries-$page`.

**Comment by liangxianzhe** [comment]
With the above change, I don't think we will go back to .arg. Closing the issue for now.
