### ISSUE TITLE
Is there a way to replace creators to return mock objects during tests?

### ISSUE THREAD

**Issue by gabime** [liangxianzhe/creator#23]
Hi,

Thanks for this project. I really like its simplicity and effectiveness. Well done!

What would be the recommended way to replace some Creators with mocks during tests (like rRiverpod’s `overrideWithValue(..)`) ?

**Comment by gabime** [comment]
Edit: probably duplicate of #15

**Comment by liangxianzhe** [comment]
Yeah, I mostly use `ref.set` and `ref.emit` to set dependencies in tests. Let me know if that works for you or not.

**Comment by gabime** [comment]
Thanks.
