### ISSUE TITLE
Graph lost after context switch with showDialog

### ISSUE THREAD

**Issue by jhoogstraat** [liangxianzhe/creator#26]
Hi,

inside a dialog, shows with `showDialog`, reading a `Creator` works, but watching does not.
Riverpod has the option to create a new `ProviderScope` inside the dialog, to be able to access the data.

**Comment by liangxianzhe** [comment]
Hi, I think you can wrap the dialog in a CreatorGraphData class, and pass `context.ref` to it. See https://github.com/liangxianzhe/creator/blob/master/packages/creator/lib/src/creator_graph.dart

I'm not with my laptop and I didn't verify it, but let me know if it works or not.

**Comment by jhoogstraat** [comment]
Weird. By wrapping the `AlertDialog`s content in a separate widget and the having a `Watcher` does rebuild the affected widgets as expected, even without a `CreatorGraphData`

**Comment by liangxianzhe** [comment]
Do you have a minimal repro?

**Comment by liangxianzhe** [comment]
@jhoogstraat It works for me too without a `CreatorGraphData`. Closing.
