### ISSUE TITLE
Question: How to use Creator with mutable state?

### ISSUE THREAD

**Issue by fritzrehde** [liangxianzhe/creator#28]
Hi, I'm currently learning Flutter, and have understood the basics of Provider so far. However, I am looking for a more elegant solution, and decided to give this a try. I am building a simple audiobook player. For that, I have to keep a list of audiobooks as internal state (that is mutable because I need to be able to add audiobooks). The documentation for this project is pretty good, but I noticed that only immutable types are put into the `Creator`. How would I turn an `Audiobooks` class (simply a list of `Audiobook`s) into a `Creator`? `Audiobooks` isn't inherently immutable like `int` or `String`, since I need to add and remove audiobooks on demand. I think
```dart
final audiobooksCreator = Creator.value(Audiobooks());
```
is wrong, but I can't figure out how else to do it.

I think the concept behind Creator and Riverpod is immutable state, and on every update/set a whole new object is provided. I think this is somewhat of a problem for another use-case I have: For the audioplayer itself (which provides an API like pause(), play()), I am just wrapping an `AudioPlayer` from `just_audio`. How would I make this AudioPlayer mutable global state with `Creator`.

Sorry if these questions are very basic, I really tried to use the docs to figure this out, but what I tried doesn't seem to work. Would be happy to get some tips/hints!
Also not sure if this is the best platform for questions, maybe you can enable the discussions feature on GitHub.
Thanks

**Comment by liangxianzhe** [comment]
Hi,

For a list of `Audiobooks`, you can simply create a new list every time the data in the list changes. For example, when adding new item, `return [...old_list, new_item]` instead of `old_list.add(new_item)`.

For the `audioplayer`, you will need to wrap it with your own data model. For example, it could be a class with one field `is_playing`. When the state changes, you call audioplayer library. Your UI and controller logic should only change `is_playing` state and respond to state change.

**Comment by fritzrehde** [comment]
Ok, I think I somewhat understand what you're getting at. For the audioplayer, I still don't understand how/where I would store the just audio AudioPlayer I am wrapping. Do I store it as an attribute in the the class with the attribute isPlaying, and then somehow "move" that AudioPlayer to a new object when I create it? Does dart have such move semantics (I come from Rust)?
Thanks for the help!

**Comment by fritzrehde** [comment]
I'm also curious if this immutability is a design decision, or if the implementation is impossible without it. What are advantages of this? Naively, I would think it involves a lot of copying/creating new objects unnecessarily, i.e. creating some overhead.

**Comment by fritzrehde** [comment]
Do you maybe have example code (maybe some existing open-source project that you know of) that has a similar architecture to what I'm trying to build?

**Comment by liangxianzhe** [comment]
> Do I store it as an attribute in the the class with the attribute isPlaying, and then somehow "move" that AudioPlayer to a new object when I create it?

I was thinking a class that takes in AudioPlayer in its constructor, and a attribute isPlaying, whose set method would call AudioPlayer's pause resume method.

> I'm also curious if this immutability is a design decision, or if the implementation is impossible without it.

That's a common pattern in UI or functional areas. Otherwise, it is hard to abstract the concept of a general state change.

> Do you maybe have example code (maybe some existing open-source project that you know of) that has a similar architecture to what I'm trying to build?

It's hard to say without knowing more of your use case. Though I'm planning to open source a large project in the coming months.

**Comment by fritzrehde** [comment]
If I pass a just_audio AudioPlayer via the constructor, where do I store that AudioPlayer? That's mutable state as well, and needs to be stored separately?

**Comment by liangxianzhe** [comment]
Never mind, it seems that AudioPlayer needs no initialization. Here is one example, similar to https://dartpad.dev/?id=1a4c338fdf8ef7c4af8f80ddff88f4ec

```dart
final _player = AudioPlayer();

// Hide the creator with file level private variable.
final _isPlaying = Creator.value(false);

// Expose the state related APIs.
bool isPlaying(Ref ref) => ref.watch(_isPlaying);
void play(Ref ref, Uri uri) {
  _player.play(uri);
  ref.set<bool>(_isPlaying, true);
}
void pause(Ref ref) {
   _player.pause();
  ref.set<bool>(_isPlaying, false);
}
```

**Comment by liangxianzhe** [comment]
Hi, I hope you get what you need. Closing this issue but feel free to reopen if needed.
