### ISSUE TITLE
Any way to retrieve/pass ref, not from the UI side?  

### ISSUE THREAD

**Issue by qronos-ai** [liangxianzhe/creator#7]
Hi Terry,

The below code updates `Text(myAccountID(ref))` each time `setAccountID(ref, 'newID')` was called. 
```
final Creator<String?> _accountID = Creator<String?>.value(null, name: 'Account ID');
String? myAccountID(Ref ref) => ref.watch(_myAccountID);
void setAccountID(Ref ref, String? value) => ref.set(_myAccountID, value);
```
I have a case where the `_accountID` is not used in UI but used as a variable (document ID) in `Emitter<Account>.stream...` from Firestore. `setAccountID` is being called not from the UI side but from a class Controller.
```
class Controller extends Something {
  _doSomething() {
    if (firebaseUser != null) {
      setAccountID(ref, 'firebaseUser.uid');
    }
  }
}
```
**1. How can `ref` be passed or retrieved in this class?**

**2. `ref.recreate` is one interesting item that I am quite curious about. I would probably use it to reset variables to default states. Is there a `ref.recreateAll`?**

---------

Just sharing my feedback. I came across Creator through Medium's recommendation of your article. Found 'Graph' very interesting, (the nodes, its elements and the edges... did a little googling on graph data structure... pardon me if I am wrong...). In my own opinion, I would say Creator is not the easiest to understand as compared to GetX but definitely much easier and straight-forward than 39 state management libraries. I have only 1.5 years of dev experience and I am still lost with the other libraries (except Getx and setState) and it took about 2 days for my 42-year-old frail brain to grasp Creator.

I did my own small performance/memory comparison (listview of network images with texts and search function), Creator vs GetX's Rx/GetBuilder. I must say I am quite pleased with the preliminary outcome particularly on memory usage. The only thing with Creator is that there is slightly a little more to code.

I like the "defining creators in global variables". It is really convenient. No more worries that I will forget to inject dependencies.

Anyway, I will be attempting to switch to Creator for my published marketplace apps. Hopefully, the apps can gain an overall performance boost.

**_Look forward to more interesting updates and examples, medium articles and growing popularity on Creator!_**

**Comment by terryl1900** [comment]
Hi @iamshaunwu, thanks for trying out the library and sharing your feedback.

As for the questions:

1. Does something like this works for you?
```
final controllerCreator = Creator((ref) => Controller(ref), keepAlive: true);
```
However, it means when you need to use the controller, you need to use `ref.read(controllerCreator)`. I guess you will likely have a ref by then, for example, through `context.ref`.

2. That's an interesting question. The closest thing I have now is `ref.disposeAll()`. However, it removes everything from the graph, if you could add things back, they will be in the default state.

Implementing something like `ref.recreateAll` is not impossible, but would be tricky, since we probably don't want derived creators being recreated multiple times. Do you mind sharing your use case a little bit more?

And for now, maybe write a helper function `void recreateAll(Ref ref)` and just manually recreate a bunch of creators there?

As for your feedback:

1. Personally I didn't do any performance comparison, because it's not a bottleneck for my app. But I'm glad to hear that you are happy with your performance test result.

2. Sure I will add more examples to make Creator easier to understand!

Thanks!

**Comment by qronos-ai** [comment]
Thanks @terryl1900!

1. Passing of ref: Will give it a try. Sorry, I missed it where you have already mentioned under Service Locator.

2. `Ref.recreate`: I had the impression that `ref.recreate` kind of 'resets' the creators with the below counter app scenario.

```
// initial creators
countA: 0
countB: 0
sum: 0 (countA + countB)

// functions
void incrementA: countA + 1
void decrementB: countB + 2

// initial UI
Text(${ref.watch(sum)}) shows 0
```
After tapping incrementA...
```
countA: 1
countB: 0
sum: 1

// UI updates
Text(${ref.watch(sum)}) shows 1
```
After disposeAll()...
```
// Nothing is logged on debug console.
// UI has no updates. No issues here since it is disposeAll.
Text(ref.watch(sum)) shows 1
```
Then I tapped decrementB.
```
// Creators were re-added in default states then updated with new values from decrementB.
// variable updates are logged on debug console.
countA: 0
countB: -1
sum: -1

// UI has no updates
Text(${ref.watch(sum)}) shows 1
```
However, when I tried ref.recreate (all 3 variables) instead of disposeAll(),
```
// 'reset' to initial values
// variable updates logged on debug console
countA: 0
countB: 0
sum: 0

// UI updates
Text(${ref.watch(sum)}) shows 0
```
What I was trying to do here was to reset all datas to the default states (eg. clear a form) without leaving the current page. My personal opinion again for this scenario is that `ref.recreate(countA)` is much convenient than, in a non-Creator environment, re-setting 'countA = 0' or 'textA = some super duper long value'. I may have gotten `ref.recreate` concept wrongly. Of course, when I pop the current page the creators are auto-disposed off and re-added in default values when I push the page back.

3. Names for variables is super useful in logging. **How can I include a log to show something is disposed?** Would be useful to track if certain creators should be included with `keepAlive: true`.

**Comment by terryl1900** [comment]
**About recreate**:

If you want to reset a bunch of fields in a table, calling `ref.recreate` manually for those creators is the way to go. `ref.disposeAll` or even a potential `ref.recreateAll` seems overkill since they might affect other creators outside the form.

`recreate` is designed to just rerun the user-provided function. So there are three cases:

1. `Creator.value('foo')` which is equal to `Creator((ref) => 'foo')`. Recreate will reset the value to 'foo'. This is what you want.

2. `Creator((ref) => ref.watch(number) * 2)`. Recreate is basically a no-op if the number stays the same.

3. `Emitter((ref, emit) async => emit( getDataFromServer() ))`. Recreate will re-fetch the data from the server.

**About dispose:**:

Sounds good. I will add the functionality to log the dispose event. Tracked [here](https://github.com/terryl1900/creator/issues/8).

**Comment by qronos-ai** [comment]
Thanks @terryl1900! In the midst of migrating... =) 
Closing this.

**Comment by qronos-ai** [comment]
Hi @terryl1900,

I would like to ask. Inside a Scaffold, there are multiple creators (no expensive widgets though...). Wrapping only Scaffold with a Watcher populates changes when creators are updated.

**Aside from the expensive widgets, what differences would there be or things to take note when wrapping only Scaffold  with a Watcher versus wrapping each creator with a Watcher? Would the single Watcher wrap on Scaffold rebuild the whole Scaffold and its' children?**

-----

Just sharing with regard to my earlier question on passing Ref to functions in "controller" class, I found a better way to pass Ref with mixin. Do enlighten if you feel this otherwise.

1. Create a mixin.
```
mixin SomeController on StatelessWidget {
  void doSomething(Ref ref) {}
  Future<String?> getString(Ref ref) {}
}
```

2. Add mixin to UI.
```
class MyHomePage extends StatelessWidget with SomeController  {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {

    return Scaffold(
        appBar: AppBar(
          title: const Text('Counter App'),
        ),
        body:  Center(
          child: TextButton(
            onPressed: () => doSomething(context.ref),
            child: Text('Do Something'),
          ),
        ),
      );
  }
}
```

**Comment by liangxianzhe** [comment]
Hello, this is my personal account. I'm moving this project to my personal account.

As for updating scaffolding, so those creators are only used in the scaffolding widget, not its descendence, right? I guess the answer depends on your use case. Maybe imagine just using StatefulWidget, whether you want to put the states into one StatefulWidget, or split states into several widgets. The same answer should apply to using creators.

As for mixin, it sure works, as long as you don't need to construct those controllers explicitly since mixin cannot have a constructor.

**Comment by qronos-ai** [comment]
Nice, got it! Thanks for enlightening!

**Comment by qronos-ai** [comment]
@liangxianzhe Hi once again!

1. What does ref.readSelf actually do? Saw the News example but don't quite catch it. What circumstances would you use ref.readSelf.

2. While I may have yet to encounter such a use case in the midst of my migration, I would like to ask. How can a value be set on a Creator, where it gets an initial value from another Creator/Emitter then stops listening to it. It's like get 1st value, then remove the edge. 
```
/// global_variables.dart
final Emitter<Account?> _account = Emitter<Account?>.stream((Ref ref) async {
    final String? uid = firebaseUser(ref)?.uid;
    return _streamAccount(uid);
  },
);

Account? account(Ref ref) => ref.watch(_Account.asyncData).data;

final Creator<String?> _someData = Creator<String?>((Ref ref) => account?.someData);

String? someData(Ref ref) => ref.watch(_someData);

void setSomeData(Ref ref, String value) => ref.set(_someData, value);
```
```
/// UI side
...
     Text(someData(ref)),
...
```
For example,
a. When the stream receives data, the initial value for someData is "fromStream".
b. Subsequently, User A enters "UserA", which sets someData to "UserA" and continues filling up the form.
c. Assuming the account is a multi-user account, User B happens to be on the form view too, sets the someData to "UserB" and submits the form first, saving all new data to the database.
d. On User A display, someData will be refreshed as "UserB".

How can we make someData (on User A display) retain as "UserA" instead of the new data?

**Comment by liangxianzhe** [comment]
Hello!

1. `readSelf` returns the current state of the creator. It should be only used if `my_new_state = some_function( my_current_state, other_creator_state)`.

2. If you need to get the first value, I guess you could use `read` rather than `watch`.

```
final account = Emitter<Account>(...);
final accountName = Emitter<String?>( (ref, emit) => emit((await ref.read(account)).name ) );

// Since accountName is emitter, set value using Future
... ref.set(accountName, Future.value('input from user A'));
```

It seems you use helper functions to hide `_account`, then maybe you could expose a `account(Ref ref)` for ref.watch and a `accountRead(Ref ref)` for ref.read.

On another note, personally, I would only use `asyncData` in the UI layer, not in the logic layer unless I really need to differentiate loading vs data state. Using Future seems more natural in the logic layer.

**Comment by qronos-ai** [comment]
Thanks for enlightening!

**Comment by qronos-ai** [comment]
Hey @liangxianzhe.

I created an Emitter.
```
final Emitter<int?> cloudData2 = Emitter<int?>(
  (Ref ref, emit) async => emit(
    await Future<int>.delayed(const Duration(seconds: 2)).then((_) => 2),
  ),
); 
```
As per your last reply, I tried to then set a value after with `ref.set(cloudData2, Future<int>.value(10))`. However, the UI still shows 2 instead of 10.
```
            Watcher(
              (BuildContext context, Ref ref, _) => Text(
                ref.watch(cloudData2.asyncData).data.toString(),
              ),
            ),
            ),
```
What did I miss out?

**Comment by liangxianzhe** [comment]
Hey sorry. My bad. It seems setting Emitter with Future.value doesn't change Emitter.asyncData. Let me see what can be done there.

In the meantime, maybe something like this?
```
final account = Emitter<Account>(...);

final accountName = Creator<String?>.value(null);
final accountListner = Emitter<void>( (ref, emit) {
  final account = await ref.read(account)); // Just read once
  ref.set(accountName, account.name);
} ) );

// When the user make changes
... ref.set(accountName, 'input from user A');
```

**Comment by qronos-ai** [comment]
Hey thanks for the quick reply. Will give it a try and update if any issues.

**Comment by qronos-ai** [comment]
@liangxianzhe I am experiencing some challenges on streams and hot reload. I am on VSCode, Flutter 3.0.5 and testing on real device - iPhone 13 Pro Max. Here's my code.
```
Creator<String?> sellerID = Creator<String?>.value(
  null,
  name: 'Seller ID',
  keepAlive: true,
);

final Creator<int> mainViewTabIndex = Creator<int>.value(0, name: 'Main View Tab Index');

final Emitter<SellerAccount?> streamSeller = Emitter<SellerAccount?>.stream(
  (Ref ref) => _streamSellerAccountFromFirestore(ref.watch(sellerID)),
  name: 'Seller Account,
  keepAlive: true,
);

final Emitter<List<Order>?> streamOrders = Emitter<List<Order>?>.stream(
  (Ref ref) => _streamOrdersFromFirestore(ref.watch(streamSeller.asyncData).data?.uid),
  name: 'All Orders',
  keepAlive: true,
);

final Emitter<List<Order>?> activeOrders = Emitter<List<Order>?>(
  (Ref ref, Function(List<Order>?) emit) async {
    final List<Order>? results = await ref.watch(allOrders).then(
          (List<Order>? value) => value
              ?.where(
                (Order order) => order.orderStatus != OrderStatus.completed,
              )
              .toList(),
        );
    emit(results);
  },
  name: 'Active Orders',
);

// DashboardView (UI layer)
                          Watcher(
                            (BuildContext context, Ref ref, _) => Text(
                              ref.watch(activeOrders.asyncData).data != null
                                  ? ref.watch(activeOrders.asyncData).data!.length.toString()
                                  : '0',
                            ),
                          ),
```
App launches...
- a UID (firestore docID) is assigned to `sellerID`
- `streamSeller` works fine. No issues here for now
- `streamOrders` retrieves only 9 out of 16 docSnapshots
- `mainViewTabIndex` updates correctly when switching tabs

On hot-reload... 
- `sellerID` is reseted to `null`
- `mainViewTabIndex` is reseted to 0, view returns back to first tab
- `streamSeller` then now returns a `null` 
- however, `streamOrders` now retrieves 15 out of 16 docSnapshots

Can you shed some light as to: 
1. Why would hot-reload reset sellerID and mainViewTabIndex?
2. As for `streamOrder`, why were only 9 docs retrieved upon launch and then another 6 docs on hot-reload, more importantly, shouldn't `streamOrder` return a null instead after hot-reload since it is dependent on `sellerID`/`streamSeller` that are already nulled?

> If T is a list, create a new list rather than update the existing one.
3. I am a bit lost with lists. The `activeOrders` appears correctly on Watcher widget. However, I am not sure if the way I code is correct. Do advise. Thanks in advance.

**Comment by liangxianzhe** [comment]
I cannot see a problem with the code. I think you will need to figure out why sellerID goes back to null. Try to find a minimum working code to repro the issue. Hot reload is fine to me if using the code below. Set sellerID, then hot reload, and sellerID stays the same.

```
import 'package:flutter/material.dart';
import 'package:creator/creator.dart';

Creator<String?> sellerID = Creator<String?>.value(
  null,
  name: 'Seller ID',
  keepAlive: true,
);

void main() {
  runApp(CreatorGraph(child: const MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Counter example')),
        body: Center(
          child: Watcher((context, ref, _) {
            return Text('${ref.watch(sellerID)}');
          }),
        ),
        floatingActionButton: FloatingActionButton(
          // Update state is easy.
          onPressed: () => context.ref.set<String?>(sellerID, 'Foo'),
          child: const Icon(Icons.add),
        ),
      ),
    );
  }
}
```

As for list. Your code is fine. The below code is not:

```
final List<String> names = ...;

final a = Creator<List<String>> ( (ref) {
  names.add('foo');
  return names;
});
```
Because from the library's view, previous state (names) == current state (names), there is no state change.

**Comment by qronos-ai** [comment]
> Because from the library's view, previous state (names) == current state (names), there is no state change.

Does this also apply to an emitter stream that returns a list? I was wondering if this could be the reason why my `streamOrders` only retrieves 9 at a start where there should be 16 documentSnapshots actually.
```
final Emitter<List<Order>?> streamOrders = Emitter<List<Order>?>.stream(
  (Ref ref) => _streamOrdersFromFirestore(ref.watch(streamSeller.asyncData).data?.uid),
  name: 'All Orders',
  keepAlive: true,
);

Stream<List<Order>?> _streamOrdersFromFirestore(String? sellerID) {
  return FirebaseApi.to.firestore
      .collection('orders')
      .where('sellerID', isEqualTo: sellerID)
      .where('orderDate', isGreaterThan: Timestamp.fromDate(DateTime.now().subtract(const Duration(days: 30))))
      .orderBy('orderDate', descending: false)
      .snapshots()
      .map((QuerySnapshot<Map<String, dynamic>>? querySnapshot) {
    if (querySnapshot != null && querySnapshot.docs.isNotEmpty) {
      final List<Order> list = <Order>[];
      for (int i = 0; i < querySnapshot.docs.length; i++) {
        list.add(Order.fromDocumentSnapshot(querySnapshot.docs[i]));
      }
      return list;
    }
    return null;
  });
}
```

**Comment by liangxianzhe** [comment]
Firestone returns new list so that's fine. If you go to Emitter.stream's source code, you can copy how it works and implement an emitter listen to stream manually. Then you can print something to see where is the problem.

**Comment by qronos-ai** [comment]
Hi @liangxianzhe, just updating you on previous issues that I had.

**1. Hot-reload resets creators/emitters** 
This is resolved. I had a DevicePreview() wrapped over MyApp() and I wrapped CreatorGraph over MyApp() thus in every Ctrl+S then hot-reload, all values were "recreated". I moved CreatorGraph() as top wrapper of everything else in runApp() and done.

**2. Missing documents from Stream?**
My bad. I overlooked some fields while sorting. Emitter is smooth and perfect.

**Comment by liangxianzhe** [comment]
Great! Thanks for sharing the root cause. That could help others in future.

So have you finished all migration?

**Comment by qronos-ai** [comment]
No problem. Glad to share them.

I am still in the midst of migrating my marketplace buyer/seller apps from GetX, while at the same time, refactoring some codes and making UI changes. GetX is easy and 'magical', however, depending on your projects, it can be a problem when they get bigger, like in my case... =P 

At times, GetX would only allow certain navigations or UI portions on a controller that can make the controller super cluttered. An example would be GetX's `Worker` that is an event listener. You would create workers inside controller class and put them under `onInit`. When certain event happens, you need to push/pop a view or show AlertDialog/Bottomsheet, and you can only do so inside the controller. (I think there could be other non-recommended alternative ways but so far, I can't think of a better one other than the above...)

Now, Creator also has a listener that is in a `Watcher` widget and IMO, it makes the flow and coding cleaner when added on the UI layer. In the below code, I added a `Watcher A` right above MyApp() to start an `authListenerEmitter` that listens to `uidEmitter` and updates `isAuthCreator` throughout the app lifecycle. When the initial SplashPage (which has a `Watcher B`) is built, `Watcher B` watches `isAuthCreator` and pushes to the relevant page accordingly.
```
runApp(
      CreatorGraph(
        child: DevicePreview(
          enabled: false,
          builder: (BuildContext context) => Watcher(
            null,
            listener: (Ref ref) {
              /// add global listeners here
              ref.watch(authListener);
            },
            child: const MyApp(),
          ),
        ),
      ),
```
This is my approach on the redirection of pages based on event. Compared to GetX, while magical, you will still need to manually dispose the workers followed by controller and reinit the controller again if you return to the SplashPage. 

Whereas on Creator, a Watcher's listener is automatically disposed after leaving its page (since this Watcher is not longer on screen) and automatically recreated when returning to SplashPage (because Watcher widget is built again). 

This is how I understand. Can you share your best practices on listeners? Do you use them to handle navigations based on certain events?

**Comment by liangxianzhe** [comment]
You understanding is totally correct, and that's how I use listener to start background jobs.

As for routing and auth, I'm using go_router, so my answer would be too specific to that library. But it is similar to what you described.

**Comment by qronos-ai** [comment]
Referencing to https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/redirection.dart, it uses `ChangeNotifierProvider` wrapped over `MaterialApp.router`. In `GoRouter()`, param `refreshListenable` is Listenable. 

EDIT: Were you able to fulfil a Watcher with listener in replace of ChangeNotifierProvider-GoRoute.redirect + refreshListenable?

**Comment by liangxianzhe** [comment]
Something like this. Will add a full example but I don't have time at the moment.

```
// auth
final self = Emitter<User?>((ref, emit) async {...}, name: 'self', keepAlive: true);
```
```
/// Allowed urls. Enum is safer than strings.
enum Url {
  // System
  home('/'),
  login('/login'),
  setting('/setting'),
  splash('/splash'),
  ;

  final String url;
  const Url(this.url);
}
```
```
/// Notifier bridges creator with go_router.
class RouterNotifier extends ChangeNotifier {
  RouterNotifier(this._ref) {
    _ref.watch(_listener);
  }

  final Ref _ref;

  /// This notifier will not rebuild since _listener always generate a void.
  /// _listener will rebuild when login user changes and notifier go_router.
  late final _listener = Creator((ref) {
    ref.watch(self);
    notifyListeners();
  }, name: 'routerNotifier');
}

/// go_router creator.
final goRouter = Creator((ref) {
  return GoRouter(
    routes: <GoRoute>[
      // System
      GoRoute(path: Url.home.url, builder: (_, __) => const HomeScreen()),
      GoRoute(path: Url.login.url, builder: (_, __) => const LoginScreen()),
      GoRoute(path: Url.setting.url, builder: (_, __) => const SettingScreen()),
      GoRoute(path: Url.splash.url, builder: (_, __) => const SplashScreen()),
    ],
    redirect: (state) {
      if (ref.read(self.asyncData).status == AsyncDataStatus.waiting) {
        return Url.splash.url;
      }
      // Note here we read instead of watch, so we don't rebuild this creator
      // when login user changes. We rely on refreshListenable to do the work.
      return ref.read(self.asyncData).data == null &&
              state.subloc != Url.login.url
          ? Url.login.url
          : null;
    },
    refreshListenable: RouterNotifier(ref),
  );
}, name: 'goRouter', keepAlive: true);
```
```
// main.dart

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final router = context.ref.watch(goRouter);
    return MaterialApp.router(
      theme: AppTheme(br: Brightness.light).themeData,
      darkTheme: AppTheme(br: Brightness.dark).themeData,
      routeInformationProvider: router.routeInformationProvider,
      routeInformationParser: router.routeInformationParser,
      routerDelegate: router.routerDelegate,
      debugShowCheckedModeBanner: false,
      title: 'My App',
    );
  }
}
```

**Comment by qronos-ai** [comment]
Hey thanks a million! I should be able to work it out from here. No worries. You go get busy. =)

**Comment by liangxianzhe** [comment]
A nice thing about this is it can route without context if needed. `ref.read(goRouter).go('some url')` works fine.

**Comment by qronos-ai** [comment]
Hi @liangxianzhe,

I have the following code.
```
// in a watcher widget wrapping MyApp()
ref.watch(authStream);
ref.watch(user);

// globalVar.dart
final Emitter<User?> authStream = Emitter<User?>.stream(
  (Ref ref) => FirebaseAuth.instance.authStateChanges(),
  name: 'Firebase Auth Stream',
  keepAlive: true,
);

final Emitter<User?> user = Emitter<User?>(
  (Ref ref, Function(User?) emit) async {
    final User? results = await ref.watch(authStream);
    emit(results);
  },
  name: 'User',
  keepAlive: true,
);
```
1. When the app is launched with no previous authenticated user, debug console shows the following statuses and datas of both creators.
```
authStream.asyncData: status = waiting / data = null
user.asyncData: status = waiting / data = null
```

2. After login, debug console displays `[Creator] Firebase Auth Stream: User(...)`. However, on print(), debug console shows the following.
```
authStream.asyncData: status = waiting / data = null
user.asyncData: status = waiting / data = null
```

3. Next, after a hot-restart, then on print(), debug console shows the following.
```
authStream.asyncData: status = active / data = User(...)
user.asyncData: status = active / data = User(...)
```

4. Followed by a sign out, then on print(), debug console shows the following.
```
authStream.asyncData: status = active / data = null
user.asyncData: status = active / data = null
```

Points 3 and 4 are correct. 1 is correct too since the creators are still awaiting for data from a login? Point 2 is the issue. This happens only to Firebase Auth stream and the `user` Emitter when the app is first launched without a previous authenticated user. I don't encounter this issue with Firestore streams. I also tried to do a `FirebaseAuth.instance.currentUser` and it returned a valid user. I did a `recreate(authStream)` to see if it streamed the authenticated user but to no avail. Have been trying for the past few days. 😂😂😂

Any issues with my code?

**Comment by liangxianzhe** [comment]
Hey, I'm not following on point 2, where did you do the print command?

**Comment by qronos-ai** [comment]
On the LoginView with a TextButton(onTap: () => print().

**Comment by liangxianzhe** [comment]
Hmm, I'm not quite sure. My wild guess is maybe your router refresh mechanism or device preview mechanism somehow mess things up. If you could have a minimum reproducible example, I can debug against my firebase project too.

Otherwise, maybe debug by attaching a customized logger to CreatorGraph. The default logger doesn't print changes related asyncData creators. The below one print everything.

```
class MyCreatorObserver extends CreatorObserver {
  const MyCreatorObserver();

  @override
  void onStateChange(CreatorBase creator, Object? before, Object? after) {
    debugPrint('[Creator] ${creator.debugName}: $after');
  }

  @override
  void onError(CreatorBase creator, Object? error) {
    debugPrint('[Creator][Error] ${creator.debugName}: $error');
  }
}

...CreatorGraph(observer: const MyCreatorObserver(), child: const MyApp())
```

**Comment by qronos-ai** [comment]
Noted. I'll give it a try later and update you. I am using Go Router like what you shared previously.

**Comment by qronos-ai** [comment]
@liangxianzhe tried to figure out how I could reach out to you in private but anyway, I wanted to share that I just published an introductory article in medium [here](https://medium.com/@shaunwu/i-getx-ed-and-went-away-with-creator-a-flutter-state-management-library-a6ff90080508). Feel free to read it. Apart from the top story section, do let me know if there is any mis-information on the technical part.

**Comment by liangxianzhe** [comment]
Hey, @iamshaunwu thanks for the article! I like it and I'm glad to see your point of view!

As for technical details, all seems correct to me, a minor fix would be "ref.create that recreates a Creator/Emitter" should be "recreate".

**Comment by qronos-ai** [comment]
Oops. Will amend it. Thanks!

**Comment by qronos-ai** [comment]
@liangxianzhe 

In the below code, after pushing `SecondPage()`. 
- `counter` is disposed
- `name` is not disposed

Shouldn't name be automatically disposed too? I doubt it is related to TextField because TextField was automatically disposed too.

```
final counter = Creator.value(0);
final name = Creator.value('shaun');

void main() {
  runApp(CreatorGraph(child: const MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('My App')),
        body: Center(
          child: Column(
            children: [
              TextField(
                onChanged: (value) => context.ref.set(name, 'terry'),
              ),
              Watcher(
                (context, ref, _) {
                  return Text('${ref.watch(counter)}');
                },
              ),
              TextButton(
                onPressed: () => Navigator.pushAndRemoveUntil<void>(
                  context,
                  MaterialPageRoute<void>(
                      builder: (BuildContext context) => const SecondPage()),
                  (Route<dynamic> route) => false,
                ),
                child: Text('To Page 2'),
              ),
            ],
          ),
        ),
        floatingActionButton: FloatingActionButton(
          // Update state is easy.
          onPressed: () =>
              context.ref.update<int>(counter, (count) => count + 1),
          child: const Icon(Icons.add),
        ),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Second Page')),
        body: Center(
          child: Column(
            children: [
              TextButton(
                onPressed: () => Navigator.pushAndRemoveUntil<void>(
                  context,
                  MaterialPageRoute<void>(
                      builder: (BuildContext context) => const MyApp()),
                  (Route<dynamic> route) => false,
                ),
                child: Text('To My App'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by liangxianzhe** [comment]
Hey, so `name` is only set but not watched? In that case, it is not disposed. Maybe I should add "or set" to this part:

```
It is added to the graph when firstly being watched **or set**.
It can be removed from the graph manually by Ref.dispose.
If it has watchers, it is automatically removed from the graph when losing all its watchers, unless keepAlive property is set.
```

Since name is not "losing all its watchers", so it is not disposed.

**Comment by qronos-ai** [comment]
Yup. `name` is not being watched. So if there is a `ref.set`, then it has to be manually disposed. Then I guess we will also need to include `ref.update` because I just tested and it is not disposed too.

Pardon me, I made some minor amendments below.

```
It is added to the graph the first time it is being watched, **ref.set or ref.update**.
It can be removed from the graph manually with Ref.dispose.
If it has watchers **only**, it is automatically disposed from the graph when losing all its watchers, unless keepAlive property is set to true.
```

Just for knowledge purposes only. What's your view on auto-disposing `ref.set` or `ref.update`?

**Comment by liangxianzhe** [comment]
The library has no way to know when to dispose name. You can totally set name in page 1 and watch name in page 2.

Or we could choose to throw an exception if someone set/update a creator which is not in the graph. I feel (not strongly though) it is an unnecessary limitation.

**Comment by qronos-ai** [comment]
Ah you are right, it makes sense.

**Comment by qronos-ai** [comment]
Hi hi!

I have a quick question.

Why is it that `ref.update<int>(counter, (int value) => value++)` doesn't update the value but `ref.update<int>(counter, (int value) => value + 1)` does?

On a side note, here's my boring [2nd article](https://medium.com/@shaunwu/how-i-divorced-with-getx-for-creator-and-why-part-1-null-33f4d2c84a1c) for your reading pleasure.

**Comment by irmhonde** [comment]
> // ref.update() docs 
Set state of creator using an update function. See [set]. No-op if the state doesn't change.

in `ref.update<int>(counter, (int value) => value++)` `value++` is a mutation on `value`, it does not return a result making the update a no-op since `value` remains the same.

Try:

```dart
void main() {
  int value = 0;
  print(value++) // prints 0
}
```

while `ref.update<int>(counter, (int value) => value + 1)` returns a new state.

Try:
```dart
void main() {
  int value = 0;
  print(value + 1) // prints 1
}
```

this also returns a new state

```dart
ref.update<int>(counter, (int value) {
  value++; // mutates value incrementing it by 1 without returning a result 
  return value;
});

**Comment by qronos-ai** [comment]
Ah. I missed this out. @irmhonde Thanks!
