### ISSUE TITLE
How can I use creator with isolate?

### ISSUE THREAD

**Issue by CalsRanna** [liangxianzhe/creator#9]
I was wondering if there is a way to use ref in a new isolate if I want to do some heavy work for example?

**Comment by liangxianzhe** [comment]
I think you could manually create a `Ref` object and pass it around in your isolate processing functions, something like [this](https://github.com/liangxianzhe/creator/blob/master/packages/creator_core/example/main.dart). Does it work?

**Comment by CalsRanna** [comment]
Seems like it can not get the creator defined in the main ui . is there a way to solve it ?

**Comment by liangxianzhe** [comment]
I think that's how isolate works. From the [doc](https://api.dart.dev/stable/2.17.6/dart-isolate/Isolate-class.html):
```
All Dart code runs in an isolate, and code can access classes and values only from the same isolate. Different isolates can communicate by sending values through ports (see [ReceivePort](https://api.dart.dev/stable/2.17.6/dart-isolate/ReceivePort-class.html), [SendPort](https://api.dart.dev/stable/2.17.6/dart-isolate/SendPort-class.html)).
```

**Comment by CalsRanna** [comment]
Got it, I see my problem.
